create table if not exists player
(
    id         bigint generated by default as identity
    primary key,
    name       varchar(255),
    ship_count integer
);

alter table player owner to postgres;

create table if not exists game
(
    id          bigint generated by default as identity
    primary key,
    player_1_id bigint
    constraint fkhb6lo8wimwbyxscrufrnedmsa
    references player,
    player_2_id bigint
    constraint fki0o6uxbqxp8dsmwyhsrcyslw8
    references player,
    shooter_id  bigint
    constraint fkomnpyj08ev1h9r5qfiyt6lr4e
    references player,
    winner_id   bigint
    constraint fkdaoa02um96nkw564trbq0jhxg
    references player
);

alter table game owner to postgres;

create table if not exists ship
(
    id          bigint generated by default as identity
    primary key,
    player_id   bigint
    constraint fk8asgv7b220o680ujjdilemhon
    references player,
    location_x  integer,
    location_y  integer,
    length      integer,
    destroyed   integer
    constraint ship_destroyed_check
    check (destroyed = ANY (ARRAY [0, 1])),
    orientation varchar(255)
    constraint ship_orientation_check
    check ((orientation)::text = ANY
((ARRAY ['VERTICAL'::character varying, 'HORIZONTAL'::character varying])::text[]))
);

alter table ship owner to postgres;

create table if not exists ship_section
(
    id             bigint generated by default as identity
    primary key,
    ship_id        bigint
    constraint fkoib9gq9nbl7tfrgli1efgkxg1
    references ship,
    player_id      bigint
    constraint fkai1j05fmpi8stbgh6vonc8ky9
    references player,
    location_x     integer,
    location_y     integer,
    section_number integer,
    destroyed      integer
    constraint ship_section_destroyed_check
    check (destroyed = ANY (ARRAY [0, 1]))
);

alter table ship_section owner to postgres;

